### ISSUE TITLE
Bitcoin Optech newsletter #292 march 11 2024

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#11]
final link -  https://drive.google.com/file/d/1cW_Lp8dZKDld7tphFBBVkvR0vvUPR4JU/view?usp=drive_link

News - 02:20
PSBTs for multiple concurrent musig2 signing sessions
16:25- Discussion about adding more BIP editors 
23:48 - Gitlab backup for bitcoin core GitHub project 
36:00 - releases and release candidates 
46:45 - Notable code and documentation changes

**Comment by VirdiJatin** [comment]
Youtube link : https://youtu.be/yb97TjvVLHA?si=K_9wjlifG6-HbN1p

👨‍✈️ Attention all Bitcoin buffs! Fasten your seatbelts and prepare for a turbulent ride as we unravel the mysteries of Bitcoin URIs and explore the pivotal role of a BIP editor. 💼  Don't miss your boarding call to join the geeky side of Bitcoin! 

hey @rajarshimaitra, need for tweet..

**Comment by rajarshimaitra** [comment]
Tweeted: https://x.com/bitshala_org/status/1783091763730661808
