### ISSUE TITLE
Optech newsletter #290 Feb 26th 2024

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#15]
final link : https://drive.google.com/file/d/1vxZLixbhdIKztYjyustFUNnXJq1Zndlk/view?usp=drive_link

02:06- News
19:44 - Thinking about mempool incentive compatibility 
39:14 - Cashu and other ecash system design discussion 
40:03 - what is Cashu?
41:00 - What's a blind signature scheme?
51:18 - Continued discussion about 64-bit arithmetic and OP_INOUT_AMOUNT opcode
58:55 - Improved reproducible ASMap creation process 
01:03:05 - Changes to services and client software 
01:09:35 - Releases and release candidates 
01:09:51 - Notable codes and documentation changes

**Comment by VirdiJatin** [comment]
yt link : https://youtu.be/w_Cpw-sFlnM?si=XMKVewkrSGQ_5-iT


📣 📰 Discover what's 'Latest in Bitcoin Tech' and revisit our vibrant discussions on mempool incentive compatibility and e-cash systems. Don't miss out! it's time to learn, leverage, and level up your Bitcoin IQ.🧠

hey @rajarshimaitra, need for tweet..

**Comment by VirdiJatin** [comment]
Hey @rajarshimaitra, Reping for tweet..

**Comment by rajarshimaitra** [comment]
As this one is very old, we can commit the tweet. Closing this..
