### ISSUE TITLE
BitshalaReadingClub_2024-01-03T16_10_20.854Z (General White Paper walkthrough)

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/reading-club#2]
https://drive.google.com/file/d/1bJwoLzaCoLnfTqirbiV6bbUezE0lpXI9/view?usp=drive_link

Here are the timelines for topics:  (Reading club_2024-01-03)
1:30 - abstract 
7:07 - Digital signature
11:30 - introduction 
12:40 - why bitcoin on one hand does seem a simple system?
15:00 - with bitcoin you can send as low as 1000Rs and high as 1000 crore 
22:00 - Timestamp server 
27:05 - proof of work
34:12 - percentage of CPU power still allows you to produce that many bitcoin blocks?
42:34 - QNA
47:22 - 5 Network
52:40. - 6 Incentive 
55:30 - uncle's blocks / Orphan blocks?
57:45 - 7 Reclaiming disk space
58:54 - 8 simplified payment verification 
1:00:00- combining and splitting value
1:02:03 - privacy
Calculations
1:08:08- conclusion
1:10:10 - QNA
1:20:15 - how lightning network compares to bitcoin network?

**Comment by rajarshimaitra** [comment]
@shreyanjoshi can you please add a suitable description for youtube below? 

Above is the timeline of the video created by Jatin. 

@paperpsych we need a YouTube thumbnail for the same. (Reading club: White paper walkthrough by Shreyan).

**Comment by shreyanjoshi** [comment]
On the auspicious occasion of the Genesis Block Day, we conducted Bitcoin Reads Special on the Bitcoin Whitepaper. 
Hosted by our Community Champ Shreyan Joshi, with technical breakdown of concepts by Professor X himself, Rajarshi Maitra, we cover everything there is to know about Bitcoin the idea, promises and assumptions made in the Whitepaper, technologies used in Bitcoin, etc along with anecdotes and QnA session towards the end. 

Related Links: 
What is Genesis Block Day?: https://calendar.bitbo.io/genesis-day/
Bitcoin Whitepaper: https://bitcoin.org/bitcoin.pdf

**Comment by shreyanjoshi** [comment]
Please feel free to make any edits, suggest changes, etc.

**Comment by VirdiJatin** [comment]
hey @shreyanjoshi what will be the name of this video for publishing on youtube?

**Comment by shreyanjoshi** [comment]
I think it should be simple and crisp - 
'Genesis Block Day Special: Bitcoin Whitepaper Technical Walkthrough'

Let me know if you have any ideas or suggestions.

**Comment by VirdiJatin** [comment]
Yeah its good.. we'll go with that!!

**Comment by VirdiJatin** [comment]
@rajarshimaitra, Here's the private link..
https://studio.youtube.com/video/luYYnNsu29A/edit

**Comment by rajarshimaitra** [comment]
Tweet: https://x.com/bitshala_org/status/1748949648671146261?s=20
