### ISSUE TITLE
Wednesday reads : Gradually Then Suddenly May 14 2024

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#24]

**Comment by VirdiJatin** [comment]
hey @paperpsych  need for thumbnail..

**Comment by paperpsych** [comment]
![Bitshala Gradually then Suddenly](https://github.com/Bitshala/reading-club/assets/149538435/f57c2309-f3e2-4599-911f-a8b928e05ba7)

@VirdiJatin Here ya go !!
