### ISSUE TITLE
Bitcoin Optech newsletter #281 24-01-07

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/reading-club#3]
https://drive.google.com/file/d/1UtrVsfxD27oA9mVDyGeZbhwQBzpfMHZy/view?usp=drive_link

Here are the timelines:  Sunday Optech 2024-01-07 #281

1:00 - discussion about griefing liquidity
2:45 - setu's question 
8:15 - setu discussion on sats
10:21 - what is a griefing attack?
14:34 - changes to services and client software 
19:40 - bitcoin network simulation tool warnet
23:48 - payjoin client for bitcoin core 
24:46 - call for community block arrival
28:07 - Envoy 1.4 released
30:40 - Anmol's discussion on coin selection 
33:44 - BBQr encoding scheme announced 
38:30 - Zeus v0.8.0
41:40- what are the rules related to CPFP free bumping?
45:14 - how the total number of RBF replaced transactions calculated?
48:20 - what type of RBF exist?
53:10 - what are hash functions used in bitcoin?
53: 49 - LDK #2685
54:18 - Libsecp256k1 #1446
55:24 - Btcpay server

**Comment by rajarshimaitra** [comment]
@QureshiFaisal 

Please add a suitable youtube description for the video. Use the timeline above in the description or modify if needed.

**Comment by rajarshimaitra** [comment]
I think this is the description written by @QureshiFaisal before. Please confirm.

Description:
In this episode we discussed:
Griefing liquidity advertisements on dual-funded LN channels
Stratum V2 RFI and its features, Warnet Bitcoin simulation tool, BBQRs and other software releases
Some hand-picked Bitcoin stack exchange questions
Updates to libsecp256k1, BTCPay server & much more.

Website: https://bitshala.org/
Community: https://discord.com/invite/atjEPVTdsQ
Newsletter: https://bitcoinops.org/en/newsletters/2023/12/13/

**Comment by VirdiJatin** [comment]
hey @paperpsych thumbnail needed for this one..

**Comment by QureshiFaisal** [comment]
> I think this is the description written by [@QureshiFaisal](https://github.com/QureshiFaisal) before. Please confirm.
> 
> Description: In this episode we discussed: Griefing liquidity advertisements on dual-funded LN channels Stratum V2 RFI and its features, Warnet Bitcoin simulation tool, BBQRs and other software releases Some hand-picked Bitcoin stack exchange questions Updates to libsecp256k1, BTCPay server & much more.
> 
> Website: https://bitshala.org/ Community: https://discord.com/invite/atjEPVTdsQ Newsletter: https://bitcoinops.org/en/newsletters/2023/12/13/

Yes, that's the one. Should be good to go.

**Comment by QureshiFaisal** [comment]
> https://drive.google.com/file/d/1UtrVsfxD27oA9mVDyGeZbhwQBzpfMHZy/view?usp=drive_link
> 
> Here are the timelines: Sunday Optech 2024-01-07 #281
> 
> 1:00 - discussion about griefing liquidity 2:45 - setu's question 8:15 - setu discussion on sats 10:21 - what is a griefing attack? 14:34 - changes to services and client software 19:40 - bitcoin network simulation tool warnet 23:48 - payjoin client for bitcoin core 24:46 - call for community block arrival 28:07 - Envoy 1.4 released 30:40 - Anmol's discussion on coin selection 33:44 - BBQr encoding scheme announced 38:30 - Zeus v0.8.0 41:40- what are the rules related to CPFP free bumping? 45:14 - how the total number of RBF replaced transactions calculated? 48:20 - what type of RBF exist? 53:10 - what are hash functions used in bitcoin? 53: 49 - LDK #2685 54:18 - Libsecp256k1 #1446 55:24 - Btcpay server




> https://drive.google.com/file/d/1UtrVsfxD27oA9mVDyGeZbhwQBzpfMHZy/view?usp=drive_link
> 
> Here are the timelines: Sunday Optech 2024-01-07 #281
> 
> 1:00 - discussion about griefing liquidity 2:45 - setu's question 8:15 - setu discussion on sats 10:21 - what is a griefing attack? 14:34 - changes to services and client software 19:40 - bitcoin network simulation tool warnet 23:48 - payjoin client for bitcoin core 24:46 - call for community block arrival 28:07 - Envoy 1.4 released 30:40 - Anmol's discussion on coin selection 33:44 - BBQr encoding scheme announced 38:30 - Zeus v0.8.0 41:40- what are the rules related to CPFP free bumping? 45:14 - how the total number of RBF replaced transactions calculated? 48:20 - what type of RBF exist? 53:10 - what are hash functions used in bitcoin? 53: 49 - LDK #2685 54:18 - Libsecp256k1 #1446 55:24 - Btcpay server

@rajarshimaitra nothing to add.

**Comment by paperpsych** [comment]
> hey @paperpsych thumbnail needed for this one..

@VirdiJatin  Here ya go...

![Bitcoin Optech - Faisal Thumbnail](https://github.com/Bitshala/reading-club/assets/149538435/c1628bcf-a1c7-4b27-aab7-5627e1e4eaf9)

**Comment by VirdiJatin** [comment]
@QureshiFaisal @setusaurabh ping for Tweet..

**Comment by QureshiFaisal** [comment]
Tweet :   Missed our weekly Bitcoin roundup? Catch up on the latest happenings through our  reading session!  Gain insights, stay informed, and revisit the discussion.  Watch the recording now: 

@rajarshimaitra @setusaurabh

**Comment by VirdiJatin** [comment]
@setusaurabh @QureshiFaisal ping for tweet..
here's the youtube link https://youtu.be/3ykA_diiD2Y?si=1xlmPRfL9z7VbRMn

**Comment by rajarshimaitra** [comment]
Tweet publsihed: https://x.com/bitshala_org/status/1752560170188890398?s=20
