### ISSUE TITLE
Bitcoin: Optech Deepdive #284 Jan 21/24

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#4]
final edit  - https://drive.google.com/file/d/1Bi1Y6b0IQ9h_2RQRxJxYiCQbuiV2l_qM/view?usp=drive_link

timelines for Optech #284 21jan

1:15 - News
1:24 - Discussion about LN anchorsband Vlv3 transaction relay proposal
1:49 - Frequent use of exogenous fees may risk mining decentralization
2:54 - How does this out-of-band fees work?
20:46 - Implications of exogenous fees on safety, scalability and costs
26:04- Ephemeral anchors introduce a new pinning attack
29:42 - An alternative: Use of endogenous fees with presigned incremental RBF bumps
41:59 - Overall conclusion 
43:13 - LN symmetry research implementation 
Question/Answers 
57:34 - Is it necessary for block headers to have a timestamp?
58:04 - what is the difference between Median Time Past (MTP) and network adjustes time?
58:46 - Why are times conceptually very different?
59:20 - Why don't we use MTP for everything and scrap network-adjusted time?
58:38 - Why are limits enforced on how far "off" a block header's timestamp is allowed to be from the node's internal clock? 
1:00:45 - Before this PR , why would anyone attacker try to manipulate node's network adjusted time?
1:01:48 - prior to this PR, how could an attacker try to manipulate node's network adjusted time?
1:02:43 - This PR uses the node's local clock as the upper-boumd block validation time rather than network adjusted time.
1:03:30 - Does this PR change consensus behaviour?
1:04:09 - Which operation were relying on network-adjusted time prior to this PR?

**Comment by VirdiJatin** [comment]
@rajarshimaitra please upload the today's recording here..

@QureshiFaisal please provide the "video name and description" for today's session for youtube...

**Comment by rajarshimaitra** [comment]
@setusaurabh ping for the recording.

**Comment by setusaurabh** [comment]
https://drive.google.com/file/d/1ZJreWQuKpZRgQBl_3HPeGcuAn1_4RSJa/view?usp=drive_link

**Comment by QureshiFaisal** [comment]
> @rajarshimaitra please upload the today's recording here..
> 
> @QureshiFaisal please provide the "video name and description" for today's session for youtube...

Title : 
Latest in Bitcoin: Optech Deepdive #284 10 Jan

Description:
In this session we discussed:
Implications of exogenous fees on safety, scalability, and costs
Pinning attacks
Pre-signed Incremental RBF bumps
LN symmetry
PR review to Nuke adjusted time stamps

**Comment by QureshiFaisal** [comment]
@VirdiJatin  Here's the tweet 

 ☕️🎙️Brewed and ready to serve! Catch up with our latest discussion where we spill the beans on Bitcoin Tech. From mining fees to lightning protocols, grab a seat at the virtual table – our insights are piping hot and served just for you!

**Comment by VirdiJatin** [comment]
Tweet link -  https://x.com/bitshala_org/status/1762408315810910557?s=20
