### ISSUE TITLE
Bitcoin Optech Newsletter #283 (Jan 14-2024)

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#5]
https://drive.google.com/file/d/1O8udfzGeLieubwczTsL5wmkdHqHagSUI/view?usp=drive_link  (Final Video link)

Timelines Optech newsletter #283
00:52 - intro 
1:59 - Disclosure of past LND vulnerabilities
6:04 - Second vulnerability 
9:51 - Fee Independent Timelocks
18:10 - Cluster Fee Estimation 
23:51 - How to specify unsuspendable keys in description 
27:52 - V3 transaction pinning cost
36:13 - Descriptors in PSBT draft BIP
40:25 - Verification of Arbitrary programs using proposed opcode from MATT
49:07 - Pool exit payment batching with delegation using fraud proofs
54:27 - New coin selection strategies

**Comment by VirdiJatin** [comment]
@QureshiFaisal  Plz drop the video name and description for this Optech letter #283...

**Comment by QureshiFaisal** [comment]
> [@QureshiFaisal](https://github.com/QureshiFaisal) Plz drop the video name and description for this Optech letter #283...

Title : 
This Week in Bitcoin Tech: Optech Newsletter #283

Description: 

In this episode we discussed:
Disclosure of past LND vulnerabilities 
Fee-dependent timelocks 
Cluster fee estimation 
How to specify unspendable keys in descriptors 
V3 transaction pinning costs 
Descriptors in PSBT draft BIP 
Verification of arbitrary programs using proposed opcode from MATT 
Pool exit payment batching with delegation using fraud proofs 
New coin selection strategies 

Website: https://bitshala.org/
Community: https://discord.com/invite/atjEPVTdsQ
Newsletter: https://bitcoinops.org/en/newsletters/2024/01/03/

@VirdiJatin done

**Comment by VirdiJatin** [comment]
@QureshiFaisal @setusaurabh Ping for tweet.

**Comment by VirdiJatin** [comment]
@QureshiFaisal @setusaurabh ping for tweet..
here's the youtube link https://youtu.be/RqpkTxbmTEM?si=mTrOMF9gJvBrleR2

**Comment by VirdiJatin** [comment]
https://x.com/bitshala_org/status/1752562485042020729?s=20
