### ISSUE TITLE
Bitcoin Reading Club Bitcoin Development Philosophy Jan 17-2024

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#6]
https://drive.google.com/file/d/12EMucYAq6bwIcL1BDrOdGQBIonuHejIs/view?usp=drive_link

Reading Club Jan 17-2024
4:35 - History
11:19 - Scaling Approaches / Vertical Scaling 
16:11 - Horizontal Scaling 
18:14 - Inward Scaling 
30:53 - Layered Scaling 
35:51 - Conclusion 
36:29 - When shut hits the fan
37:16 - Responsible Disclosure

**Comment by VirdiJatin** [comment]
@shreyanjoshi  ping for video Youtube name and Description..
@paperpsych for Thumbnail

**Comment by shreyanjoshi** [comment]
Bitcoin Reads: Bitcoin Development Philosophy, Chapter 8 - Scaling; History, and Approaches

**Comment by shreyanjoshi** [comment]
Description:
Join us in our weekly Bitcoin Reads Session. We cover Bitcoin Development Philosophy, Chapter 8 - Scaling. 

What does Scaling mean in Bitcoin? What has its History been? What are the different approaches to solve for scaling?, etc.

Relevant Links:
Book: https://bitcoindevphilosophy.com/
Community: https://discord.gg/r4JB2pQ7

**Comment by VirdiJatin** [comment]
@paperpsych ping for thumbnail...

**Comment by rajarshimaitra** [comment]
@paperpsych Ping again for the Reading Club Thumbnail.

**Comment by rajarshimaitra** [comment]
Found this in the channel. Ping @VirdiJatin 

![Image](https://github.com/Bitshala/reading-club/assets/36541669/00964c5f-e149-4e18-8e21-6fab4ec0f59c)

**Comment by paperpsych** [comment]
@VirdiJatin this is the one for Bitcoin Dev Philosophy

![Bitcoin Dev Reading](https://github.com/Bitshala/reading-club/assets/149538435/32c5eaba-e1e6-4ef7-b2b7-66e2bb39d656)

**Comment by VirdiJatin** [comment]
https://youtu.be/ln8m4ThmYcU?si=yziNkrDGNpfvMxcR
