### ISSUE TITLE
Optech Newsletter #285 Jan 29th

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/reading-club#7]
final edit - https://drive.google.com/file/d/1xzHUQK8jiOj40Glw10kVBhSNbxuGicg3/view?usp=drive_link

timelines Optech newsletter #285
1:03 - Disclosure of past vulnerability in core lightning 
8:24 - why is this vulnerability disclosed now when it was already sorted and tackled?
10:35 - New LNHANCE combination soft fork proposed
22:29 - Proposal for 64-bit arithmetic soft fork
24:20 - Overview of cluster mempool proposal
24:46 - CPFP
35:53 - question about pinning attack 
Updated specification and implementation of bitcoin transaction compression 
38:00 - Discussion of Miner Extractable Value (MEV) in non-zero Ephemeral anchors 
46:24 - Releases and release candidates 
48:53 - Notable code and documentation changes

**Comment by VirdiJatin** [comment]
@setusaurabh ping for recording..

**Comment by VirdiJatin** [comment]
https://youtu.be/I3KEZIivMtc?si=ZKFgRiQTP6_zGOj4 

Faisal's tweet : 🚀 Ready to enlighten your Bitcoin knowledge? 🔍  Re-live the electrifying discussion where we shed light on vulnerabilities in the lightning network and delve into the intriguing world of cluster mempool. ⚡ Lightning does strike twice!

@rajarshimaitra need for tweet

**Comment by rajarshimaitra** [comment]
Tweeted: https://x.com/bitshala_org/status/1777196095900168254
