### ISSUE TITLE
Optech Deep Dive #287 Feb 5th, 2024

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/reading-club#8]

**Comment by rajarshimaitra** [comment]
@setusaurabh ping for the recording.

**Comment by setusaurabh** [comment]
https://drive.google.com/file/d/1_nWpQD9iICIu0lXEA2TgcSb31rlN555d/view?usp=drive_link

**Comment by VirdiJatin** [comment]
final video - https://drive.google.com/file/d/10hbuvQYMjYRTEWJgaskAy8B2JLCuC_A7/view?usp=drive_link 

timelines Optech newsletter #287
1:02 - kindered replaced by fee
19:41 - Opposition to CTV based on commonly requiring exogenous fees
29:00 - what is the oldest transaction which is still not gone through?
37:10 - Question/Answers form Bitcoin Stick Exchange
39:35 - How does header-first prevent disk fill attack?
41:26 - In BIP324 v2transport redundant on Tor and I2P connection?
43:00 - What is a rule of thumb for setting the maximum number of connections?
45:33 - Why isn't the upper bound (+2h) on the blue ck timestamp set aa a consensus rule?
46:58 - Sigop count and it's influence on transaction selection?
49:25 - Releases and release candidates
49:56 - Notable code and documentation changes

**Comment by VirdiJatin** [comment]
@QureshiFaisal ping for video name and description..

**Comment by VirdiJatin** [comment]
Youtube link : https://youtu.be/o7QRpPN92kc?si=9DJCDZZ-iPwzU23n

Faisal's Tweet: Get ready to witness some bewildering Bitcoin banter! 🚀 We tackled topics that'll make your head spin faster than a rollercoaster! From sibling eviction in Bitcoin Core to OP_CTV . Grab your popcorn and hit play! 🍿

@rajarshimaitra need for tweet

**Comment by rajarshimaitra** [comment]
tweet: https://x.com/bitshala_org/status/1776247018253418842

**Comment by VirdiJatin** [comment]
hey @rajarshimaitra, you can close this issue.. and mark it done
